### ISSUE TITLE
Plugin BedrockParity v2.0.0 has failed to register events for class

### ISSUE THREAD

**Issue by Coconut-2439** [tbyt/BedrockParity#5]
When I installed and tried to enable the plugin, the server got this error
服务器 thread/ERROR Plugin BedrockParity v2.0.0 has failed to register events for class com.tbyt.AnimateHeadsForGeyser because com/destroystokyo/paper/event/player/PlayerPostRespawnEvent does not exist.

Spigot1.18.2
Plugins (15): CoreProtect, SpigotPing, CustomCommandPrefix, VeinMiner, MoveLight, ViaVersion, floodgate, eBackup, ViaBackwards, LuckPerms, SkinsRestorer, Geyser-Spigot, BedrockParity, GeyserHacks, GeyserUpdater

Geyser Version:该服务器正在运行 Geyser 版本 2.2.2-SNAPSHOT (git-master-79154f3) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61)

**Comment by tbyt** [comment]
I'll look into it, I've been inactive.

**Comment by tbyt** [comment]
> When I installed and tried to enable the plugin, the server got this error 服务器 thread/ERROR Plugin BedrockParity v2.0.0 has failed to register events for class com.tbyt.AnimateHeadsForGeyser because com/destroystokyo/paper/event/player/PlayerPostRespawnEvent does not exist.
> 
> Spigot1.18.2 Plugins (15): CoreProtect, SpigotPing, CustomCommandPrefix, VeinMiner, MoveLight, ViaVersion, floodgate, eBackup, ViaBackwards, LuckPerms, SkinsRestorer, Geyser-Spigot, BedrockParity, GeyserHacks, GeyserUpdater
> 
> Geyser Version:该服务器正在运行 Geyser 版本 2.2.2-SNAPSHOT (git-master-79154f3) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61)

I notice now that you're on 1.20.4 Java. I assume in your https://github.com/TBYT/BedrockParity/blob/master/src/main/resources/config.yml in the BedrockParity folder, it is set to 0?

**Comment by Coconut-2439** [comment]
I didn't do anything, and the plugin went back to normal in a reboot. I guess it's the geyser update. Anyway, thank you!

**Comment by tbyt** [comment]
> I didn't do anything, and the plugin went back to normal in a reboot. I guess it's the geyser update. Anyway, thank you!

Great! But the error should not happen either way since you're on 1.20.4. Anything below 1.20.2 would need to have the head animations turned on. Anything above can have it off as geyser already supports it. If it was set to 0 in the config.yml then the class the error is in should not be called at all.

**Comment by tbyt** [comment]
> I didn't do anything, and the plugin went back to normal in a reboot. I guess it's the geyser update. Anyway, thank you!

Also i was looking at the geyser versions, i looked past that you're on Spigot 1.18.2. Why the use of SpigotMC as a server and not PaperMC as this plugin uses api calls to PaperMC which is why you hit the error.

**Comment by MrBsng** [comment]
I can attempt to adjust to spigot api as it seems geyser still supports it and its forks.

**Comment by MrBsng** [comment]
Now fixed in https://github.com/tbyt/BedrockParity/commit/097d3c7bb509fcff42a73100cb16d423896682f3
please download latest @Coconut-2439

**Comment by Coconut-2439** [comment]
> 现在已在 [097d3c7](https://github.com/tbyt/BedrockParity/commit/097d3c7bb509fcff42a73100cb16d423896682f3) 中修复，请在 https://github.com/tbyt/BedrockParity/releases 或 https://modrinth.com/plugin/bedrockparity 下载最新版本

Ok.Thank you for fixing it!I will.download it now.
